// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtdY8XTDlvuWOco0PThXpiQgynyrGxbcE',
    appId: '1:680147753488:web:22e2c886278338f1f38895',
    messagingSenderId: '680147753488',
    projectId: 'ikmancloneapp',
    authDomain: 'ikmancloneapp.firebaseapp.com',
    storageBucket: 'ikmancloneapp.appspot.com',
    measurementId: 'G-GW67QLGNE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkSa_tCttFjF1JjoJWplkM2MPHW3QX0ow',
    appId: '1:680147753488:android:8c21c3ec53f9fa12f38895',
    messagingSenderId: '680147753488',
    projectId: 'ikmancloneapp',
    storageBucket: 'ikmancloneapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvMFxgVxVoEDkrvuBJTX5S8PMsuZrltY',
    appId: '1:680147753488:ios:718b5f75fdc63598f38895',
    messagingSenderId: '680147753488',
    projectId: 'ikmancloneapp',
    storageBucket: 'ikmancloneapp.appspot.com',
    iosBundleId: 'com.example.ikmanCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvMFxgVxVoEDkrvuBJTX5S8PMsuZrltY',
    appId: '1:680147753488:ios:96364a57179940c6f38895',
    messagingSenderId: '680147753488',
    projectId: 'ikmancloneapp',
    storageBucket: 'ikmancloneapp.appspot.com',
    iosBundleId: 'com.example.ikmanCloneApp.RunnerTests',
  );
}
